repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
        exclude: ^cmd/examples/main.go$
      - id: go-vet
        name: go vet
        entry: go vet
        files: '^(cmd|internal|pkg)/'
        types: [go]
        language: system
        exclude: ^cmd/examples/main.go$
      - id: go-imports
        exclude: ^cmd/examples/main.go$
      - id: go-cyclo
        args: [-over=15]
        exclude: ^cmd/examples/main.go$
      - id: validate-toml
      - id: no-go-testing
      - id: golangci-lint
        exclude: ^cmd/examples/main.go$
      - id: go-critic
        exclude: ^cmd/examples/main.go$
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy
